### ISSUE TITLE
Push permissions

### ISSUE THREAD

**Issue by SamTay** [BlueAcornInc/ba-address-validation#1]
How can I get push access to this repository? I just want to push up an initial development branch. I would fork it, but this is a private repo, so that seems like a no-no.

**Comment by SamTay** [comment]
@rob-blueacorn I can't even assign you. I'm guessing it is you that needs to give me access since you created the repo.

**Comment by Skrath** [comment]
@SamTay By the way, you can fork private branches without any problems, but lemme see if I can just fix the permissions on this.

**Comment by SamTay** [comment]
Thanks. I thought that would make the forked version public, since my personal account isn't paying for the privacy.

Also, just realized this repo isn't private, so that is another issue.

**Comment by Skrath** [comment]
I added all of the teams to this repo, so you should be able to write to it now. Not sure who created this repo, but you have to add teams as collaborators after creating a new repo, by default they will not have any collaborating teams.

**Comment by briceburg** [comment]
@rob-blueacorn is this supposed to be private? can do so via [repository] settings > make private if so.

Also to reiterate -- all repositories we add both BA - Dev Team and BA - Read Team to. This ensures that our automation tools have access (via Read Team), and that Developers have push/admin access (via Dev Team). If you ever want to protect a repository, remove Dev Team -- but do leave Read Team so that our bot can still access repo.

@SamTay re: forking private repos. GitHub did this right. a fork of any private Organization repository

a) is private, no matter if your personal account is allowed private repos, and cannot be made public
b) does not count against the private repository count of the originating Organization

pretty sweet.

**Comment by SamTay** [comment]
Ah I see, that's cool. Thanks for the clarification.
